# AUTOGENERATED! DO NOT EDIT! File to edit: ../Dogs vs Cats.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'interface', 'is_cat', 'classify_image']

# %% ../Dogs vs Cats.ipynb 2
from fastai.vision.all import *
import gradio as gradio

def is_cat(x): return x[0].isupper()

# %% ../Dogs vs Cats.ipynb 4
learn = load_learner('cat_or_dog.pkl')

# %% ../Dogs vs Cats.ipynb 6
categories = ('Dog', 'Cat')

def classify_image(image):
    pred, idx, probs = learn.predict(image)
    return dict(zip(categories, map(float, probs)))

# %% ../Dogs vs Cats.ipynb 8
image = gradio.inputs.Image(shape=(192,192))
label = gradio.outputs.Label()
examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg']

interface = gradio.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
interface.launch(inline=False)
